version: 2.1
jobs:
    # create_infrastructure: 
    #     docker:
    #       - image: amazon/aws-cli
    #     steps:
    #       - checkout
    #       - run:
    #           name: Create Cloudformation Stack
    #           command: |
    #             aws cloudformation deploy \
    #               --template-file template.yml \
    #               --stack-name myStack-${CIRCLE_WORKFLOW_ID:0:5} \
    #               --region us-east-1
     # Exercise: Config and Deployment
    configure_infrastructure: 
      docker:
        - image: python:3.7-alpine3.11
      steps:
        - checkout
        - add_ssh_keys:
            # You can get this ID in the section where you registered the SSH Key
              fingerprints: ["c9:ab:c3:c2:3f:43:7f:66:bd:5f:c4:ca:7a:64:06:fe"] 
        - run:
            name: Install Ansible
            command: |
              apk add --update ansible
        - run:
            name: Run Playbook and Configure server
            command: |
              ansible-playbook -i inventory.txt main4.yml
# Sequential workflow 
workflows:
    # Name the workflow
    myWorkflow:
      jobs:
        # - create_infrastructure
        - configure_infrastructure