version: 2.1
orbs:
  aws-cli: circleci/aws-cli@2.0.3
jobs:
  configure_infrastructure: 
    docker:
      - image: python:3.7-alpine3.11
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints: ["c9:ab:c3:c2:3f:43:7f:66:bd:5f:c4:ca:7a:64:06:fe"] # You can get this ID in the section where you registered the SSH Key
      - run:
          name: Install Ansible
          command: |
            # install the dependencies needed for your playbook
            apk add --update ansible 
      - run:
          name: Run Playbook and Configure server
          command: |
            ansible-playbook -i inventory.txt main4.yml
workflows:
    myWorkflow:
      jobs:
        - configure_infrastructure
